# Generated by Django 2.2.10 on 2021-08-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
